# Acknowledgments

I am indebted to the sport and people of ski jumping. In addition to numerous mentions of Dad as a focal point of this tribute, my own honorary first tier 'Hall of Fame' of people would include:

## John Kusz

John's impressive ski jumping exploits are well documented and deservedly so. His love of the sport showed in decades long persistence to ultimately achieving his Copper Peak goal and just as much, continuing to compete at a high level several years past that. Even while the ski jumping culture evaporated in the Ironwood area, his continuing positive attitude and unflinching work ethic inspired me during the many hours of preparing the hills before we could do what we thoroughly enjoyed.

Although ultra competitive and 11 years my senior, he always treated me as a ski jumping partner. Our early morning trips to upper Midwest meets were fun and memorable, even with his intentionally lame 'Dad jokes' such as "Looks like we are now entering the town of Donot Pass." He is a sweetheart even when applying good hearted teasing. The two of us were riding in his car to do an interview at the local radio station to drum up interest in an upcoming Wolverine meet. When I pulled down the passenger visor mirror, he noted that "You don't need to look good on radio." Little did he know that I was surreptitiously trying to use the mirror to check out the girl on the side of the road that we had just passed.

## Walter (Wally) James Kusz

A member of the 'Greatest Generation', Wally rose to a rank of staff sergeant in the U.S. Army while serving in World War II. He was an accomplished gymnast and baseball player, besides making his mark as a ski jumper, including membership on the 1945 U.S. Army ski jumping team that competed in Norway and Germany. After putting his jumping skis down, he shepherded the sport in countless ways, being a driving force (and hands on labor) behind creation of the 30m Iron Bowl, the resurrected 55m Wolverine, and the ski flying Copper Peak.

A past president of the GRSC, catalyst for the local youth program in the 60's and 70's, and the master of hill preparation for Copper Peak, he covered the whole spectrum of ski jumping, while running a business. With all that going on, the brief periods of coaching that he was able to spare at the start of my jumping career were an invaluable foundation.

## Michael Kusz

In the early 70's, Mike (Wally's son) was the big brother to many of us younger Ironwood junior jumpers. One of the leading Ironwood jumpers of that period, he was as solid and steady in his jumping style as he was in guiding personalities with a congenial, yet no nonsense approach. No surprise that led Mike to an impressive legal career at several levels, while also serving the ski jumping communities in Iron Mountain and Ironwood.

## Robert Shea

As another member of the 'Greatest Generation' and close friend of Wally, Bob's kindness and support that he showed to many of us, including an introverted youngster as myself, did not go unnoticed. Even more so, his extreme dedication to the local sport was evident as one of a handful that were the real force laboring relentlessly in the off season to build or upgrade the Iron Bowl, later Wolverine, while supporting the Copper Peak initiative.

## Charles (Charlie) Supercynski

A phenomenal multi-sport athlete as a youth and young man, Charlie translated that passion for sports into being a shepherd for ski jumping. Since the early 1960's, Charlie has been the multi-purpose glue (dare I say Super-glue!) for advancement of ski jumping on the Gogebic Range. Always approachable and unassuming, he has filled so many roles over the years from behind the scenes niches not getting addressed to leading a supervisory board out front.

As a junior jumper, I enjoyed the sport while people like Charlie worked hard to bridge the gap between ski club organizations with sometimes confusing or competing objectives. Until I had classes with Charlie as professor at Gogebic Community College, I was only superficially aware of the technical skills he had applied to designing multiple ski jumps, including the Iron Bowl, the scaled down Wolverine, and the 1975 Wolverine overhaul. Through it all, Charlie has also been the unflinching flag bearer, ambassador, custodian, and documentarian for Ironwood ski jumping.

## Uncle Toivo

Willie and Toivo (Toyk) always alluded to inheriting an exceptional work ethic from their Grandpa John who had to be a fierce dynamo to establish a new homestead from scratch in the early 1900's in a harsh winter region of a new country and little to no English skills. As a soft spoken adult, Toivo (my godfather) was an avid outdoorsman who parlayed that high energy and discipline into being an avid cross country and marathon runner (which in turn his son John excelled).

He raised five kids with wife Bertha and worked more than 30 years as a welder and then foreman for the Reserve Mining Co in Silver Bay, Minnesota. In his later years, he expended boundless energy as a founding member (and sometimes called the grandfather) of the 310 mile Superior Hiking Trail, cleared out of rugged forest wilderness along the north shore of Lake Superior that today stretches from Wisconsin south of Duluth to the Canadian border.

