# The Future of Ski Jumping

## Status of Midwest Jumping

In the mid-1900's, nearly every Upper Midwest village with northern European heritage and even slightly hilly terrain had countless number of ski bumps. When contrasting today with an era nearly 50 years ago, the fact is that the number of ski jumping clubs in the U.S. has decreased dramatically. From over 160 ski jumping sites nationwide not so long ago, there remains but approximately 30 ski jumping clubs in 12 states. Of those thirty, twelve are located in the Midwest. Minnesota, a historical hotbed of ski jumping and prominent contributor to the U.S. national teams, now officially lists only 4 clubs, down from a total of 21 in the late 20th century. Regrettably, two of the most prominent Central Division clubs, Duluth and Ely, that produced numerous Olympians in the 70's and 80's era, have closed their operations.

How can the trend of a shrinking ski jumping participation be reversed? A prime example of undying commitment to the sport is the Chicago (Norge Ski Club). In the early 2000's, while safety conscious Ely Minnesota city officials discussed how to scrap the unused 70m Ely ski jumping scaffold, along came Norge Ski Club to purchase the tower for $1. They then arranged to dismantle and transport the scaffold the 540 miles to Fox River Grove on seventeen flat bed trucks and re-assemble it. Effectively, they salvaged the demise of one club for the improvement of another. Now, that's commitment.

Today, Norge is one of several ski jumping clubs that have adapted a comprehensive approach to advance the sport. It includes a jumping hill complex that provides facilities and coaching from the smallest beginner hill to a Normal hill. At Norge, an organized team of trained coaches offer to guide the earliest beginners to seasoned Olympic class jumpers. Within one complex, the jumper can graduate through sensible hill size steps of 5m, 10m, 22m, 47, and 72m.

Besides the towns listed above, other ski jumping hills and hills have sprung up in central Wisconsin, such as Cameron, Minocqua, Oconomowoc, and Rome. So, there is hope for Midwest ski jumping.

## Large Hill Facilities

Is the advancement of North American ski jumping handicapped by lack of large hill facilities?

Large hills are a necessary stepping stone to compete on the international stage, but the number of large hill ski jumps in this hemisphere is more than adequate for current and future growth of the sport. Benefiting from regional commitments, as well as major investments for several Olympics hosted in North America over the past few decades, the U.S. (and our sovereign Canadian neighbor) have a significant number of large hill facilities well distributed across the East, Midwest, and West regions.

More so, availability of large hills is not a prerequisite for the majority of ski jumping population to thoroughly enjoy the sport at recreational levels. From either an international competitive or regional recreational perspective, the answer should be a resolute 'no'. It is not a limiting factor.

Of the 200 largest ski jumps around the world, 20 are located in North America. With 10% of the 200 largest ski jumps, it argues that the high end of the ski jumping scale is covered, especially at the current level of participation in the U.S. and Canada. Of course, periodic investments for upgrades or maintenance are required for facilities as they age.

Closer to home, the upper Midwest is amply equipped with Large, Giant, and Ski Flying hills. Four of the largest seven (and six of largest twenty) ski jumps in North America are in the upper Midwest (western half of the U.P., southern half of Wisconsin, northeastern Minnesota, and northern Illinois) and situated within 100 to 400 miles of each other, including Thunder Bay, Ontario.

## North American Large Hills

| Hill Area | City | K-Point | Hill Record |
|-----------|------|---------|-------------|
| Copper Peak | Ironwood, MI | 145m | 158m |
| Olympic Park | Whistler, BC | 125m | 149m |
| Pine Mountain | Iron Mountain, MI | 120m | 144m |
| Olympic Park | Park City, UT | 120m | 139m |
| Big Thunder | Thunder Bay, ON | 120m | 137m |
| MacKenzie | Lake Placid, NY | 115m | 136m |
| Snowflake | Westby, WI | 108m | 130m |
| Howelsen | Steamboat Springs, CO | 114m | 127m |

This is not to say that today there is an adequate number of small to intermediate jumping hills to support substantial growth in the sport. Yet, it's a smaller mountain to climb when a regional groundswell for the sport arises. As may be inferred from the earlier list of Midwest clubs, there are several active small and intermediate hill ski jumping clubs in Wisconsin and Minnesota attempting to spearhead growth, motivated by an enduring fascination with the sport. They have recognized the importance of a graduated set of small hills within the same complex (ex: Madison, Iola, Wisconsin Rapids, Coleraine, Cloquet, St. Paul, and Bloomington), in addition to using hills already integral to most existing large ski jumping hill complexes.

## Foundation or Roof?

To increase popularity of ski jumping, should the priority be the development of small hills and youth ski jumping programs or large hills and international competition?

The foundation, framing, and roof are all basic and necessary elements during construction of a durable house. And with some variation, following a predefined sequence is necessary for ensuring a lasting structure. From my peanut gallery perspective, a similar philosophy applies for growing the sport of ski jumping in the U.S. The general answer to the question is that a foundation is where it starts.

In North America, a broad foundation of youth and community involvement is arguably lagging. A clear priority should be given to building from the ground up, focusing on youth and small to intermediate size hills. For ski jumping to be re-established as an integral part of the sporting culture, a critical mass of communities and families must embrace it by supporting youth oriented facilities and programs. I have high admiration for the existing ski jumping clubs continuing to propagate this approach.

Having said that, an occasional festival, such as a Copper Peak ski flying event, can complement the greater, longer term objective. Yet, it can't be the primary or sole path to resuscitate the sport on a national or even local basis. Even though I was an awestruck 8 year old witnessing Pine Mountain jumpers roaring by, it was inconceivable at that time to envision riding Pine Mountain some time later. If anything, I would have concluded that such an amazing exhibition on a massive hill, although incredible to watch, was entirely out of my reach.

On a personal note, only by a father's passion and a ski club that built a progression of jumping hills did the aspiration of riding big hills emerge and become a reality for me. As a junior class jumper, I greatly appreciated and depended on the support of the local ski club. That support included the building and maintenance of the Iron Bowl and then Wolverine hill which fortunately coincided with my junior jumping stint. Underlying all of this was local ski jumping leadership with a vision.

## The Copper Peak Story

Although I was not directly exposed to it as a youngster, internal tension existed for decades within the Gogebic Range and Wolverine Ski Clubs as to the best strategy to advance the sport of ski jumping, both locally and regionally. For the top down argument, a prominent ski flying facility would raise broader visibility to this great sport, and if accompanied by a financial windfall generated by ticket sales and TV exposure, the trickle down effect would benefit the foundation. Unfortunately, it has not panned out that way.

Once Copper Peak was birthed, the sheer magnitude of effort required of the finite sized crew saddled (or honored) with the responsibility of preparing for and executing a ski flying tournament while simultaneously trying to grow a junior / local jumping organization was exhausting and unsustainable. It is truly amazing that amidst all of the attention required to try to make Copper Peak a success, many of those same individuals were directly involved in the Wolverine rebuild and ensuring successful Wolverine meets.

The awesome accomplishment of building the massive Copper Peak ski flying facility by 1969 was started decades earlier with a stretch dream of a venerable group of ski jumping diehards. But, for a number of well documented reasons, the operational vision has not yet been realized, stifled periodically by weather misfortune, and more so, a hodgepodge of financial and organizational complexities that either were not handled well and/or could not be entirely anticipated. Suffice to say that solid financial underpinning of favorable TV contracts and 50,000 walk-up attendances so typical in Europe was not going to occur right out of the gate for an admittedly niche U.S. sport, despite ski jumping's regional legacy. Although the track history of Copper Peak does not match the vision for it yet, ski jumping enthusiasts should bristle when locals try to dump it into a coffin with a toe tag of 'white elephant'. That is not to say that the path to success will be easy without paradigm shifts in thinking and continued management creativity.

Since the last ski flying tournament in 1994, snowmobile hill climbing and extreme 400m uphill running races from bottom of the landing to the top of the scaffold have periodically complemented Copper Peak operations that have largely subsisted on fees for chair lift and elevator rides to sightsee at the top of the tower during warmer months.

## Copper Peak Revival

After several decades, optimism has become tangible for a rejuvenated and modernized Copper Peak enabling resumption of tournaments. Yet another generation of Copper Peak advocates have persevered in keeping the vision alive. Financially bolstered by a recent $20M State of Michigan grant, reprofiling of the landing hill is active, with completion targeted in the 2025-2026 timeframe. Substantial additional work is planned in 2026 to introduce artificial surfaces. These and other upgrades can position it to host international Giant hill competitions beyond the winter season.

It will be exciting to see if a multi-season calendar for Copper Peak can be established while solidifying its own financial viability with minimal reliance on European ski jumping protocol and politics. Passing those thresholds and thinking beyond local objectives, can its resurgence compliment a greater U.S. national vision for advancement of the sport of ski jumping at all levels? With so much that the sport has to offer, one has to believe this greater opportunity can be realized.

## Cultural Embrace

So, what are the prospects for a genuine cultural investment in North American ski jumping?

By a variety of progressive and creative means, a primary objective should be facilitating access of this wonderful high intensity sport to youth and family participation that spreads organically across communities. Absolutely critical to future growth and success of the sport of ski jumping in the U.S. is artificial hill coverings accompanied by lights to enable year round activity guided by a core of expert coaches. Local club administrators and national ski association(s) must share the same overall vision to relentlessly promote and support the sport.

To cultivate and expand the next generation or two of ski jumpers, more clubs must have a progressive vision, as demonstrated by several clubs in the upper Midwest and other regions of the U.S. The Park City Utah Nordic Ski Club complex offers a graduated scale of multiple hill sizes, including 10m, 20m, 42m, 68m, 100m, and 134m. As other prominent examples, similar approaches are practiced in Steamboat Springs CO, Lake Placid NY, Madison (Middleton) WI, and Eau Claire WI. On a smaller, but still impressive scale, the Iola WI Winter Sports Club keeps the dream alive with a cascade of smaller hills while offering one-on-one coaching. As a result of this, the 17 men and women nominated to the 2024 - 2025 U.S. Ski Jumping Team hail exclusively from Norge, Lake Placid, Steamboat Springs, Park City, Eau Claire, and Madison ski clubs. It is extremely encouraging to see the hope for ski jumping kept alive and thriving, at least in pockets.

## Women's Ski Jumping

Of course, the emergence of women's ski jumping adds dramatically to the potential population of ski jumpers. After Therese Altobelli and others 'broke trail' in the 70's and 80's, women's participation steadily grew more prominent so that since 1997 the U.S. national championships have been crowning a women's champion. Lo and behold, access to world championship participation followed and U.S. women won gold medals in two of the first three years that women were allowed to compete (2009–Lindsey Van, 2013–Sarah Hendrickson). By the 2014 Sochi Olympics, the staid, but economically motivated International Olympic Committee could no longer deny women from ski jumping in the Games.

## Looking Forward

At the time in 1972, I didn't fully appreciate the passion of the Kandahar junior ski jumping club from downstate (Brighton, MI) who arrived one day for an Iron Bowl junior meet, nearly 600 miles from their home base. For those more deeply familiar with the historical footprint of ski jumping, it is but one example of commitment that endures to this day. In 1928, Henry Hall led the building of a 60m ski jump near Brighton. Before being destroyed in 1937, the hill record of 201 feet was set by Ironwood's Ted Zoberski in 1936.

As a final longer cast, with artificial hills and lights, ski jumping venues shouldn't have to be limited to states with a few months of often inconsistent snowfall. OK, ski jumping requires a wholly different type of venue than most sports. But, if hockey and its massive infrastructure can be transplanted and thrive in Fort Lauderdale, Tampa Bay, LA, and of all places, Las Vegas, is it really farfetched to envision ski jumping popularized in regions reflexively thought to be illogical ski jumping sites? In contrast to alpine skiing, the footprint of ski jumping is small and access to an entire mountain range is not required. As just one out of the box idea, creative use of the towering landfills around the country could be used as ski jumping locations. In any case, ski jumping should be introduced in broader regions of the country, supported by locals that are passionate about carrying this great sport forward.

The exciting heritage of ski jumping should continue to be preserved and built upon, while shedding the shallow, antiquated perception of ski jumping being a dangerous circus act.

