# Bibliography

1. Soaring With The Eagles: The Copper Peak Story, Charles Supercynski (2012).
2. Jerry Martin - 1973 U.S. National Ski Jumping Champion (Ishpeming), Duluth News Tribune.
3. Curry Hill Ski Jump, Ironwood (1923), Gogebic Iron Range History, David Kangas.
4. Wolverine Ski Jump During 1940's Tournaments, Wolverine Nordic Trails Archives and Bob Carli.
5. Newspaper Article reference, For The Love of Skiing, Alan K. Engen, 1998.
6. Teenaged Willie Savonen Action Pose, Wendy (Savonen) Hicks.
7. Suicide Bowl Ski Jumping Tournament (circa 1940), Ishpeming Ski Club (ishskiclub.com).
8. Basic Ski Jump Hill Terminology, Ski Jumping Hill Archive.
9. Iron Bowl 30m and 15m Ski Jumps (1971), Charles Supercynski (1).
10. Telemark Landing, Eurosport.
11. Willie Savonen Junior Jumper (circa 1946), Wendy (Savonen) Hicks.
12. Craig Savonen Junior Jumper (1973), Craig Savonen.
13. Canadian National Ski Team Member Peter Wilson on Copper Peak, Ironwood Daily Globe.
14. Craig's Map of Midwest Region Ski Jumps, Craig Savonen.
15. The 'New' Wolverine in the Late 1970's, Charles Supercynski (1).
16. 1975 – 76 Gogebic Range Ski Jumping Octet at Wolverine, Ironwood Daily Globe.
17. Suicide Bowl Ski Jumping Complex (Ishpeming, Mi), Ishpeming Ski Club (ishskiclub.com).
18. Henry Hansen In Mid-Flight Rotation, Charles Supercynski (1) via Mike Andrashi.
19. Empire Stadium Ski Jump, Vancouver (1954), Tom Harris - 'Temporary Ski Jumps' (The Operable Window).
20. Soldier Field Ski Jumping (1937), fleetfeet.com.
21. Early 1970's Middleton Artificial Inrun, Madison area newspaper article.
22. 2020's Artificial Inrun Track, Olympic Explainer, Larry Lage Michigan Associated Press.
23. View From Top of Suicide Hill, Ishpeming Ski Club (ishskiclub.com).
24. Copper Peak Vista, copperpeak.net.
25. Westby Snowflake K108 Ski Jumping Hill, Snowflake Ski Club internet site.
26. Savonen at 1979 Junior National Tryouts at Wolverine, Ironwood Daily Globe.
27. Pine Mountain Scaffold (circa 1959), amazon.com.
28. Papoose Olympic Ski Jumping Hills, Squaw Valley (1960), Ski Jumping Hill Archive.
29. Westby Snowflake K108 Ski Jumping Hill, 1979 Snowflake Ski Club meet program.
30. Dave Engstrom (the Green Hornet) in Flight, David Engstrom.
31. Winter Olympic Injuries, By Sport, British Journal of Sports Medicine, Graphic Washington Post, February 2014.
32. Percentage of Athletes Losing Time to Injury in 2018 Olympic Winter Games, British Journal of Sports Medicine.
33. Ski Jumping Hill Archive, Ski Jumping Archive (skisprungschanzen.com).
34. Ski Jumps Worldwide, Ski Jumping Archive (skisprungschanzen.com).
35. Historical Ski Jumping Facilities per Country, Ski Jumping Archive (skisprungschanzen.com).
36. Olympic Ski Jumping Medal Count By Country (1924 – 2022), Compiled from "List of Olympic Medalists in Ski Jumping".
37. Matti Nykaenen – 1988 Calgary Olympics, Mark Caldwell, AFP.
38. Holmenkollen Ski Jump (1980's), unknown magazine article.
39. World Record Ski Jumping Distance, data compiled from 'List of Longest Ski Jumps'.
40. Largest Ski Jump Hills Based on Distance Record, data extracted and compiled from 'Ski Jumping Archive (skisprungschanzen.com)'.
41. Eino Wiemeri "The Flying Finn" at Wolverine (1936), Wolverine Nordic Trails Archives.
42. Newspaper Comment About Torger Tokle, For the Love of Skiing, Alan K. Engen.
43. V-Style Flight - 2001 Vintage, 2002 USSA Central Division magazine cover, Wendy Ragotzkie.
44. John Kusz in Copper Peak Flight, Soaring With The Eagles: The Copper Peak Story, Charles Supercynski, 2012 (1).
45. Active Ski Jumping Clubs U.S. Midwest (2024), compiled from Generally Available Information.
46. Large North American Ski Jumping Hills, data extracted and compiled from Ski Jumping Archive (skisprungschanzen.com).
47. 1930's View of 60m Brighton Mi Ski Jump, Genal Pratt.
48. Hill Size Classification and Examples, data Extracted and Compiled from 'The Ski Jumping Hill Archive'.
49. Scooping the Wolverine Outrun, Ironwood Daily Globe.
50. Wolverine Hill Preparation 1979, Ironwood Daily Globe.
