# The Broader View

## Athletic and Mental Merits

What about the broader view of the sport? Even though the popularity of ski jumping in the U.S. has waned over recent decades, its merits are still compelling. This centuries old pastime fulfills the pursuit of a high intensity, anaerobic athletic challenge. In short, ski jumping demands unique physical prowess and mental fortitude. Yet, both a novice and an international champion can safely enjoy the thrills it offers. By these means of classification, ski jumping is a top tier sport.

The thrill of ski jumping is multi-faceted. A ski jumper has to embrace straightaway speed down the inrun ramp, fearless commitment at take-off, unpredictable 'hang gliding-like' lift, and near weightlessness before a feather soft landing. If the ski jumping 'pilot' masters all the subtleties of efficient air flight in fluctuating winds and evolving snow conditions, he will soar down the hill. Well, that's the goalposts.

Sure, if one can afford it, weightlessness can be simulated in 20 seconds of a parabolic airplane flight, just like astronauts practice. But, the lift and duration of a ski jumper's flight (2 – 8 seconds depending on the length of the ski jumper's flight), amidst variable conditions, is directly influenced by the athlete's skill. In a parabolic airplane flight, the conditions are created by the pilot while participant's influence on the result is minimized.

Progress has been made, but the athleticism and biomechanics of an elite ski jumper defies full description. A powerful cat quick leap must be timed precisely, followed by transition into an aerodynamically efficient flight position that continuously and quickly adjusts to a sometimes cold, blustery, unpredictable environment. Ski jumpers may be viewed as fear defying adrenaline junkies that have downhill skier instincts, gymnastic agility at speeds up to 65 mph, and subliminal genius for neuromuscular coordination when handling air currents.

That aggregate of talents must be applied throughout the duration of what's called a ski jump that is much more than a jump, but has a prelude (inrun ramp), beginning (take-off), middle (flight), ending (landing) and postlude (transition to outrun). All of these jump segments must be mastered by an aggressive, but disciplined mindset that does not lose poise nor surrender to doubt, fear, or failure.

## Camaraderie

Sports that transcend the sole individual during competition are extra special. Successful team athletes allude to the joy of camaraderie while "climbing the mountain" together, celebrating, trusting, and picking up each other along the way. Sports that are more individually oriented, such as swimming, golf, or ski jumping, can also provide a similar level of fulfillment within a healthy club or team setting. In special circumstances, it is also evident across a community of competitors. Such was my experience with ski jumping.

## How Safe Is It?

OK, one may be attracted to a sport with thrills and skills, but how risky is ski jumping? With the growing sensitivity to safety in contemporary times, what is the actual (rather than widely believed), dangers of ski jumping? Unfortunately, potential new participants in ski jumping can be deterred, when in the interest of attracting audiences, ski jumping is erroneously portrayed as exceptionally dangerous. Sure, if one wants to toy with near death adrenaline levels, they might try wingsuit flying, but those risk-to-reward ratios are astronomically high. Such is just not the case with ski jumping.

What does the USA Nordic organization, an organization with a vested interest in the safety of its sport, say on the subject?

> "Ski jumping is a safe non-contact sport. Ski jumpers develop their jumping skills at their own pace. Each jumper starts out on the smallest hill with alpine skis, and progresses to the next larger hill when ready. Each skier progresses at a pace right for them with safety as the primary objective and with the input of experienced coaches who understand the importance of foundational skills necessary to keep jumping safe."

A 2012 Consumer Product Safety Commission study revealed that for children ages 5 to 14 injuries for all types of skiing occurred at a rate of 2 per 100,000 participants. Yeah, two. All of the more common sports or activities (most of them involving some form of contact), such as football, basketball, hockey, baseball, soccer, and playground ranged from 51 (hockey) to 584 (football) injuries per 100,000 participants.

Within the overall sport of skiing, 2006 - 2008 International Ski Federation (FIS) data concluded that injuries causing lost time for training or competitions on a per athlete basis was 15% - 35% less for ski jumping than that of alpine skiers and snowboarders.

## Olympic Injury Data

In a more comprehensive study, the British Journal of Sports Medicine reviewed the frequency of injuries for the 2914 athletes from 92 countries participating in the 2018 Winter Olympics at PyeongChang, South Korea. Data was compiled for percentage of athletes losing time for training or competition to injury.

All injuries that prevented training or competing impacted less than 7% of the ski jumping participants. That's equivalent to curling! Meanwhile, half pipe skiing, snowboard cross and ski cross, snowboard slopestyle, and aerials led the injury parade at 4X – 5X that frequency. Moreover, a majority of injuries in those sports resulted in longer downtimes. Amongst the intermediate to high range for injuries were alpine skiing, bobsled, ice hockey, speed skating, and luge. Figure skating, cross country skiing, and freestyle mogul skiing occupied the low end of injury scale. Trailing the entire pack with the least amount (<1%) of injuries are those gun toting biathlon folks (thankfully) and nordic combined (which includes ski jumping as part of their regimen).

If such data is surprising, further inspection should prove it to be intuitive. The impressive aerial skills of halfpipe skiers executing multiple twists, turns, and inversions followed by a mostly vertical descent and (hopefully) an upright landing onto an uneven hard snow terrain makes even superior athletes susceptible to injury.

Another relatively new sport, ski cross (formally organized in 1986 and adopted as an Olympic sport in 2010), has four competitors simultaneously racing side by side down a course full of bumps and turns. Their objective is to survive a progression of exciting, but aptly named, knockout rounds to win a championship. The likelihood of contact or injury inducing falls are supported by the data. Without being too poetic, contrast that with a single, well trained ski jumper soaring majestically through the air and touching down gently on an expertly profiled and smoothly groomed landing hill.

## The Agony of Defeat

Vinko Bogataj is the poster child for instilling alarm about ski jumping dangers. You almost certainly know of him, if you were born in the 90's or earlier. He's the poor chap from Yugoslavia (now Slovenia) whose cartwheel off the side of the inrun of a West German ski jump in March 1970 was immortalized as the Agony of Defeat at the beginning of every Wide World of Sports show before ABC cancelled the show in 1998.

A ski jumper of any skill level falling in the inrun is as rare as Halley's Comet swinging by Earth. The rest of Vinko's story is that he indeed suffered a concussion and broken ankle, but resumed training by June of that same year. Living in eastern Europe, he didn't know he was (in)famous until invited to a Wide World of Sports anniversary show in 1981 where Vinko received a standing ovation from a huge assembly of famous athletes, with Muhammad Ali himself requesting his autograph.

There is a combination of natural and trainable skills to reduce the possibility and/or severity of injury when a ski jumping fall occurs. Once it is obvious that a normal flight and landing is unrecoverable, the seriousness of the fall can usually be mitigated by piloting to a flat lying position and adhering to the hill surface as quickly as possible.

On the few times that I fell (1 - 3 times per season), they were almost all uneventful. I was fortunate and never held a yard sale, nor did I personally witness a fall by any other jumper that required immediate medical attention. But, as I tease others when alpine skiing or playing euchre, if you aren't occasionally falling or failing, you aren't really pushing the boundaries and learning. 'Going to the edge' certainly applies to achieving winning times in alpine downhill skiing, but to a lesser degree in the discipline of ski jumping.

::: {.dictionary}
**Yard sale** – slang for an epic, violent wipeout where a skier's equipment (skis, gloves, goggles, helmet, etc..) is scattered all over the landing hill.
:::

## Historical Relevance

In the deep snow of the prehistoric world, transportation and hunting was facilitated by strapping sticks of wood to one's feet. Archaeological finds near today's border of Russia and Finland indicate that skis were used at least as early as 6000 BC. In those millenniums, leaping into the air with skis was probably inconceivable unless trying to scale a crevasse while chased by a saber tooth tiger.

Ski jumping as a recognized pastime originated more than 200 years ago, with Norway attributed as the birthplace, but it hasn't been a curiosity isolated to Scandinavia. During the late 19th and early 20th century, northern Europeans streamed into the U.S. to work the mines, forests, and farmlands and brought their culture with them, which included their favorite sport of skiing, and in particular, ski jumping. There was a natural affinity for it, encouraged by a sense of family legacy. Perhaps fondness for a sport associated with bravado was to be expected in an era where everyday adult life was otherwise dominated by monotonous, exhausting, and yet hazardous nature of being a miner, logger, farmer, or housewife.

Whereas the first recorded ski jump (31 feet) is commonly credited to Norwegian Ole Rye in 1808, the first recognized North American competition of the transplanted sport was held in St. Paul, Minnesota as early as 1887, less than two decades after the first formal competition in Norway.

In the first 75 years of the 20th century, many American kids were playing baseball nearly every summer day on the streets or farm fields. In the winter, in any hilly neighborhood of the Northeast, upper Midwest, or Rocky Mountains blessed with snow, countless ski jumps (or bumps) of all sizes would appear.

## Ski Jumping Worldwide

The worldwide enthusiasm and cultural impact of ski jumping is evidenced by the sheer number of ski jumps that existed over the past century. As of November 2025, over 9000 ski jumps and 7000 ski jumping facilities have been catalogued by the massive and still growing Ski Jumping Hill Archive. It is undoubtedly neither complete nor will it ever include the countless smaller 'backyard bumps' that many communities used to have.

From an historical account, over 9000 ski jumps and 5154 ski jumping facilities in 48 countries have been identified. The discrepancy in numbers is explained by the process of identifying ski jumps and/or facilities naturally occurs before the details are developed and entered into the archive.

As a subset of this database, and an indication of ski jumping's continuing popularity, today there are still nearly 1600 active ski jumps worldwide. The historical popularity of ski jumping is also evident by the count of jumps either 'out of order' or 'destroyed' over the years. There are handfuls of ski jumps now under construction and more on the drawing board, pending adequate resources to proceed. Artificial surfacing has now been applied to nearly two thirds of them (1013), thus expanding the ski jumping season even when or where there is no snow.

On a country-by-country basis, a dozen countries have had more than 100 different ski jumping facilities, with Norway leading by far, Germany a distant second, and the U.S. in third. European and western Asian countries are also prominent. However, the extent of ski jumping diaspora is exponentially greater when noting not only Australia and New Zealand on the list, but Algeria, Chile, Lebanon, and Morocco! Wow.

Regarding the 300+ U.S. ski jumping facilities, they existed across 28 states, with Wisconsin, Minnesota, and Michigan having the highest count. In Michigan alone, 31 facilities were built over the years and nearly half of them were located in the Lower Peninsula, including the southerly cities of Brighton, Grand Rapids, Fenton, Oxford, and Detroit!

